### ISSUE TITLE
Store user input directly as char

### ISSUE THREAD

**Issue by mayisa87** [tscripca/HangMan#11]
https://github.com/tscripca/HangMan/blob/90106f2c936c4f0ac63b65622c40b0f5912782c0/HangMan/Program.cs#L59

Instead of always calling userLetter.KeyChar, store the value to a char directly and use this char then in code.
Makes code again more readable.

**Comment by henrikmdev** [comment]
I think Isabella just wants you to use a char variable instead of a ConsoleKeyInfo variable. Because when you use the ConsoleKeyInfo variable, you have to use "userLetter.KeyChar" everywhere in the code. It would be more readable if you used a char variable instead.

Is that right Isabella?

**Comment by mayisa87** [comment]
Yes exactly!
