### ISSUE TITLE
Hardcoded constant introduces dependency

### ISSUE THREAD

**Issue by incredibleLeitman** [tscripca/HangMan#2]
https://github.com/tscripca/HangMan/blob/9015219cfeaa0878178bda33603e3ef2e0fb527f/HangMan/Program.cs#L9
https://github.com/tscripca/HangMan/blob/9015219cfeaa0878178bda33603e3ef2e0fb527f/HangMan/Program.cs#L10

Instead you could make the "LAST_CHANCE" value depending on "MAX_TRIES" like
```const int LAST_CHANCE = MAX_TRIES - 1;```

However, I don't think you need an extra constant for that but can just use "MAX_TRIES - 1" in your code

**Comment by mayisa87** [comment]
if your "LAST_CHANCE" value should be always MAX_TRIES decreased by 1, it makes no sense to store it in a constant. It means that lastChance will be always calculated by MAX_TRIES-1

calculations are OK. Constants are used for values that stay the same over your whole program.
