### ISSUE TITLE
Check for right winning conditions

### ISSUE THREAD

**Issue by mayisa87** [tscripca/HangMan#8]
Check for your winning condtion to be done right.

**So summing up:**

- If user guesses at least one letter right, he will be asked for the whole word
- if user reaches the last iteration (max tries reached) and no letter was guessed so far, user is asked for the whole word to guess too.

https://github.com/tscripca/HangMan/blob/a4a945356f39fb8144d41312c71ba6f78e768761/HangMan/Program.cs#L67-L70
At this point, in this block, you know that a letter was guessed right. You could simply store this information, that there was a right guess, to a boolean. 

IF you want to go for an exact counter, you can define an int, and increase it at this point.
DANGER: Multiple occurances... if you want to cover this too, this could be an solution? having a boolean just for current letter, checking if the counter was already increased, if already increased, do not again :)

```
//will be reset again to false at next user input
bool currentLetterMatched = false;
for (int i = 0; i < randomHiddenWord.Length; i++)
{
    if (userLetter.KeyChar == randomHiddenWord[i])
    {
       currentLetterMatched = true;
        if (!currentLetterMatched)
        {
           counterLettersGuessedRight++;
        }
        displayedLettersList[i] = userLetter.KeyChar;
    }

    Console.Write(displayedLettersList[i]);
}
```

**Comment by tscripca** [comment]
![Screenshot 2023-07-08 223943](https://github.com/tscripca/HangMan/assets/109100094/492de49f-8006-4431-9563-940ab59c7ef4)
The " counterLettersGuessedRight " that supposed to keep track of how many time I've guessed the correct letter doesn't want to reset after the first game. Is there any way that I can reset this after the first round is finished?

**Comment by tscripca** [comment]
> ![Screenshot 2023-07-08 223943](https://github.com/tscripca/HangMan/assets/109100094/492de49f-8006-4431-9563-940ab59c7ef4)
> The " counterLettersGuessedRight " that supposed to keep track of how many time I've guessed the correct letter doesn't want to reset after the first game. Is there any way that I can reset this after the first round is finished?

I think that issue regarding the " counterLettersGuessedRight " increment is sorted now. I've moved the initialisation before the main for loop and it resets back to zero every time you start a new game.

**Comment by mayisa87** [comment]
![image](https://github.com/tscripca/HangMan/assets/130921606/9debff66-334b-44e9-9541-fb90b471195d)


I'm sure you will hate me now, but if you remove currentLetterMatched and change the if to

```
  if (!displayedLettersList.Contains(userInputLetter))
  {
      counterLettersGuessedRight++;
  }

```
So before replacing the underline by guessedLetter, you check if the guessedLetter is already in list (won't be for first match of letter in word) and increase counter. If the letter appears more often in the word, it will be already in list for second character found in word, and counter won't increase again. 

It will work too. I don't know why I had such a complicated view on this issue, it seems that I was confused already too.
